### ISSUE TITLE
复现中的疑问

### ISSUE THREAD

**Issue by lyyaixuexi** [YanjingLi0202/Q-ViT#11]
在复现Q-Deit-T (4-bit)时，复现最终达到的结果只有acc1 66.3, acc5 86.9 具体训练配置如下，请问有什么参数是需要额外设置的嘛，训练用的卡是6张Titan XP
        --epochs 300 \
        --warmup-epochs 0 \
        --weight-decay 0. \
        --batch-size 84 \
        --data-path /mnt/cephfs/mixed/dataset/imagenet \
        --lr 3e-4 \
        --repeated-aug \
        --output_dir ./test \
        --distillation-type hard \
        --teacher-model deit_tiny_patch16_224 \
        --opt fusedlamb \
        --eval

**Comment by YanjingLi0202** [comment]
> 在复现Q-Deit-T (4-bit)时，复现最终达到的结果只有acc1 66.3, acc5 86.9 具体训练配置如下，请问有什么参数是需要额外设置的嘛，训练用的卡是6张Titan XP --epochs 300 --warmup-epochs 0 --weight-decay 0. --batch-size 84 --data-path /mnt/cephfs/mixed/dataset/imagenet --lr 3e-4 --repeated-aug --output_dir ./test --distillation-type hard --teacher-model deit_tiny_patch16_224 --opt fusedlamb --eval

您好，应该是--teacher-model  vit_deit_tiny_distilled_patch16_224。非常抱歉readme文件中的命令出现了错误，已修正。
