### ISSUE TITLE
why use torch.clip in Q-MLP

### ISSUE THREAD

**Issue by Pang-Yatian** [YanjingLi0202/Q-ViT#4]
Hi, Thanks for your great work.

May I ask why add this line to Q_MLP?
```
        x = torch.clip(x, -10., 10.)
``` 
Is there any specific reason? To make training stable? or this trick will improve performance?
https://github.com/YanjingLi0202/Q-ViT/blob/0cee463b82d39b6572dbbf3d4aaa4b72afe849d6/quant_vision_transformer.py#L138-L147

**Comment by YanjingLi0202** [comment]
We use the torc.clip() here to limit the outliers, but the specific parameters, i.e.  "-10., 10." here have not yet been explored sufficiently. We also removed the torc.clip() here conducting experiments, and found that the performance on the Deit-tiny model decreased by about 0.1%

**Comment by Pang-Yatian** [comment]
Thanks.
